import crypto from "crypto";

import type { Request } from "express";

export function getDeviceFingerprint(req: Request): string {
  const userAgent = req.headers["user-agent"] || "";
  const accept = req.headers["accept"] || "";
  const ipAddress = req.ip || req.connection.remoteAddress || "";

  const raw = `${userAgent}|${accept}|${ipAddress}`;

  return crypto.createHash("sha256").update(raw).digest("hex");


}


// it return a device id  for the user based on the request headers and IP address. The device id is generated by concatenating the user-agent, accept header, and IP address, and then hashing the resulting string using the SHA-256 algorithm. This ensures that the device id is unique for each combination of user-agent, accept header, and IP address, making it useful for identifying unique devices or sessions in a web application.
// this function generates a unique device fingerprint based on the request headers and IP address. It uses the SHA-256 hashing algorithm to create a hash of the concatenated string of user-agent, accept header, and IP address. This fingerprint can be used for various purposes, such as identifying unique devices or sessions in a web application.

//its useful for security purposes, such as preventing fraud or abuse, and can also be used for analytics and tracking user behavior across different devices.